name: CICD

on:
    push:
        branches: [ "main" ]
env:
    IMAGE_NAME: cicd_test
    IMAGE_TAG: latest
    ENV_FILE: ${{ secrets.ENV_FILE }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
            ref: main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.11.7'
      - name: Installing dependencies
        run: pip install pylint
      - name: Run App
        run: python ./src/main.py
      - name: Test App
        run: python ./src/testcalculator.py
      - name: Run Linters
        run: |
            cd src
            pylint calculator.py
            pylint main.py
            pylint testcalculator.py
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: |
            docker build . --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Push the image on DockerHub            
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /etc/test_cicd
            touch aaa.txt
            echo AAA > aaa.txt
            echo "${{ secrets.SECRETS }}" > .env
            ${{ secrets.SSH_COMMAND }} 
