name: CICD

on:
    push:
        branches: [ "main" ]
env:
    IMAGE_NAME: cicd_test
    IMAGE_TAG: latest
jobs:
  CI_CD:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
            ref: main
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
##            python-version: '3.11.7'
#      - name: Installing dependencies
#        run: pip install pylint
#      - name: Test App
#        run: python ./src/testcalculator.py
#      - name: Run Linters
#        run: |
#            cd src
#            pylint calculator.py
#            pylint main.py
#            pylint testcalculator.py
#      - name: Build docker image
#        run: |
#            docker build . --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
#            docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#            username: ${{ secrets.DOCKER_USERNAME }}
#            password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Push the image on DockerHub            
#        run: |
#            docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
#            docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NEURO_SSH_HOST }}
          username: ${{ secrets.NEURO_SSH_USER }}
#          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.NEURO_SSH_PORT }}
          key: ${{ secrets.NEURO_SSH_KEY }}
          script: |
              touch final.txt
#            ${{ secrets.SSH_COMMAND }} 
