name: CICD

on:
    push:
        branches: [ "main" ]
env:
    IMAGE_NAME: cicd_test
    IMAGE_TAG: latestt
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
            ref: main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.11.7'
      - name: Installing dependencies
        run: pip install pylint
      - name: Run App
        run: python ./src/main.py
      - name: Test App
        run: python ./src/testcalculator.py
      - name: Run Linters
        run: |
            cd src
            pylint calculator.py
            pylint main.py
            pylint testcalculator.py
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build . --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Push the image on DockerHub            
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#      - name: Build and push the image
#        run: |
#         docker login --username deniel369 --password ${{ secrets.FEDAG_TOKEN }} ghcr.io
#          docker build . --tag ghcr.io/fedagcom/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#          docker push ghcr.io/fedagcom/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#      - name: executing remote ssh commands using password
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          port: ${{ secrets.SSH_PORT }}
#          script: |
#            ${{ secrets.SSH_COMMAND }}
