name: CICD

on:
    push:
        branches: [ "main" ]
env:
    IMAGE_NAME: tm-front
    IMAGE_TAG: dev
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'
      - name: Installing dependencies
        run: pip install pylint
      - name: Run Linters
        run: |
          cd src
          pylint .\*
      - name: Test App
        run: python TestCalculator.py
      - name: Run App
        run: python main.py
#      - name: Build and push the image
#        run: |
#         docker login --username deniel369 --password ${{ secrets.FEDAG_TOKEN }} ghcr.io
#          docker build . --tag ghcr.io/fedagcom/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#          docker push ghcr.io/fedagcom/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#      - name: executing remote ssh commands using password
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          port: ${{ secrets.SSH_PORT }}
#          script: |
#            ${{ secrets.SSH_COMMAND }}
